elitak/nixos-infect

- nixos-infect
See https://github.com/NixOS/nixpkgs/pull/17784
> Use NIXOS_LUSTRATE

- README.md
- nixos-infect
The main change is to make the script work when there is only one network interface : eth1 configuration is added only if present.
I managed to make it work on small OVH VPS instances ( https://www.ovh.com/us/vps/vps-ssd.xml )
> optional eth1, works on OVH VPS

- nixos-infect
Fixes all errors and warnings reported by Shellcheck. I don't believe this fixes real issues though.
> Shellcheck

- README.md
- nixos-infect
Allow to boot and configure the machine in one go
> NIXOS_IMPORT option

- nixos-infect
this let me enable the eth1, but i still have some network problems. any idea if this is already tested?
> fix eth1 rule

- nixos-infect
> nixos 18.09 -> 19.03

- nixos-infect
When the -z returned false, the script would return its error code, 1, resulting in a failure.
> Use if rather than test before rebooting

- nixos-infect
Fix both issues cited in this [comment](https://github.com/elitak/nixos-infect/issues/18#issuecomment-508904427).
> Fix error code 1 on empty file for grep

- README.md
- nixos-infect
Simply bumps the NixOS version to 19.09 and updates the README.
> Use NixOS version 19.09

- nixos-infect
I had to make some changes to be able to nixos-infect a Debian 10 (buster) VPS.
> Debian 10 fixes

- README.md
I followed @DavHau's modified instructions in #48 and they worked for me. The fewer instructions are needed, the better!
Resolves #48.
> Update Hetzner instructions

- README.md
The script was tested on Ubuntu 20.04 and it works just fine
> Add DO: Ubuntu 20.04 (LTS) x64

- README.md
> Updated README.md with OVHcloud test on Arch Linux

- README.md
Signed-off-by: Pamplemousse <xav.maso@gmail.com>
> Update README.md for OVHcloud on Debian 10

- README.md
- nixos-infect
- Add EFI support (required for AArch64 instances on OCI)
- Support non-ext4 root file systems (Oracle Linux images use XFS)
> Add support for Oracle Cloud Infrastructure

- README.md
Hello!
Works fine with both the nixos-21.05 and nixos-unstable channels.
Thanks a lot for this script :bow:
> Update README for Debian 11 on Hetzner Cloud

- README.md
- nixos-infect
NixOS 21.11 has been released 🎉
https://nixos.org/blog/announcements.html#21.11
> Update default nixpkgs version to 21.11

- README.md
- nixos-infect
NixOS 22.05 has been released 🎉
https://nixos.org/blog/announcements.html#nixos-22.05
> Update default nixpkgs version to 22.05

- README.md
Tried it out today and it works well.
The new instance page lets you configure User-Data not but a startup script so use that instead.
> Update README.md for Ubuntu 22.04 on Vultr

- README.md
Just tested with this provider and the script worked like a charm.
> Added Clouding.io to the list of hosts that work.

- README.md
- nixos-infect
Requires the same static network config that digital ocean does.  Tested working on 20.04.
> add ServArica

- README.md
Tested a while ago (Nov 2020), but worked great.
Also, a few small layout improvements.
> Add Scaleway as a tested provider

- nixos-infect
Not exactly a game changer or anything, just a minor fix to an oddity. :)
> Fix ESP backup file path

- README.md
- nixos-infect
[NixOS 22.11](https://nixos.org/blog/announcements.html#nixos-22.11) was released last December.
> Update default nixpkgs version to 22.11

- README.md
Tested on Ubuntu 22.04 and 22.10 and update the results in the README.md file.
> README.md: Update DigitalOcean in README.md

- README.md
Managed to successfully install NixOS 22.11 over Ubuntu 20.04 64b on a RackNerd shared VPS. Thank you!!!!!! 💖💖💖
> readme: add RackNerd success, with notes

- README.md
Fixes #139
I also tested it with Ubuntu 22.04 and Debian 11 today.
> Changed Hetzner Cloud installation instructions to cloud config

- nixos-infect
> use 23.05 as default version

- README.md
Continuation of https://github.com/elitak/nixos-infect/pull/172
> chore(docs): Update channel version to 23.05

- nixos-infect
> Resolved symlink to nixpkgs channel before passing to nix-env command
