- nixos-infect
This tweaks nixos-infect to be allow infecting some Hetzner servers (tested against CX10).
Also, add some fallbacks (useful for debugging new backends)
I hope, I didn't fkuped the disk detection for DigitalOcean (line 50).
(I do know about NixOps Hetzner backend, but I'd like nixos-infect to support more backends)
> support Hetzner vServer

- nixos-infect
Was getting errors:
```
trace: warning: The option `ip6' defined in `/etc/nixos/networking.nix' has been renamed to `ipv6.addresses'.
trace: warning: The option `ip4' defined in `/etc/nixos/networking.nix' has been renamed to `ipv4.addresses'.
```
> update ip4/ip6 configuration keys per 18.03 warnings

- nixos-infect
DigitalOcean uses static IPs so no point having dhcp daemon running and errors in the log…
> disable dhcp

- nixos-infect
The problem was that some VPS (from GigaCloud provider, Ukraine) provided `ens3` interface
name, but after infection it was renamed to `eth0` via udev rules.
This fixes hardcode in two ways: 
- actually fix hardcode
- specify `networking.usePredictableInterfaceNames` explicitly
I thinkg, both approaches can replace each other (and work in combo too). So, we can leave udev rules and drop usePredictableInterfaceNames, leave usePredictableInterfaceNames and drop udev rules, or leave both. I've chose the last variant here, because I can't test this on Digital Ocean.
Also, this partially overlaps with https://github.com/elitak/nixos-infect/pull/17 (and maybe closes it).
> Fix hardcode of eth0 in several places

- nixos-infect
During my nixos-infect tests I have sometimes canceled infection in the middle.
Rerun of nixos-infect failed because there were some old swap files, which
were no longer available as swap devices.
`swapoff -a` will handle this for us (we are going reboot anyway)
> more robust removeSwap

- nixos-infect
Useful when nixos-infect is used within programs that manage the
machine's state, like nixops.
See e.g. [this](https://github.com/NixOS/nixops/blob/264fc018041fa0e856a55fa3f63a62a7d3e6e4fc/nixops/backends/digital_ocean.py#L189-L195) for a case in which the machine's state is handled outside nixos-infect.
> add NO_REBOOT variable

- nixos-infect
Running nixos-infect on DigitalOcean on smallest droplets with Fedora 30 results in dnf crash during the CheckEnv phase. 
`(remote-exec):   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current`
`(remote-exec):                                  Dload  Upload   Total   Spent    Left  Speed`
`(remote-exec):   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0`
`(remote-exec): 100  8626  100  8626    0     0  45882      0 --:--:-- --:--:-- --:--:-- 45882`
`(remote-exec): /usr/bin/curl`
`(remote-exec): /usr/bin/dnf`
`(remote-exec): Fedora Modular 30 - x86_64                      3.0 MB/s | 2.1 MB     00:00`
`(remote-exec): Fedora Modular 30 - x86_64 - Updates            4.3 MB/s | 2.9 MB     00:00`
`(remote-exec): Fedora 30 - x86_64 - Updates …
> Making swap sooner as dnf under DigitalOcean requires more memory

- nixos-infect
This helps Hetzner Cloud, which doesn't populate routes by
default and thus network doesn't work.
Fixes https://github.com/elitak/nixos-infect/issues/25
Didn't test DigitalOcean, Vultr and other providers.
> Make routes config explicit.

- nixos-infect
This adds support for lvm.
Detecting the devices for boot loader installation / file system is done in two separate steps now.
Tested on vultr, digital ocean, genesis cloud (uses lvm).
> Add LVM support

- nixos-infect
closes #43 
With this change the parsing of the authorized_keys file should become fully compatible to all variations allowed by this definition:
```
AUTHORIZED_KEYS FILE FORMAT
AuthorizedKeysFile specifies the files containing public keys for public
key authentication; if this option is not specified, the default is
~/.ssh/authorized_keys and ~/.ssh/authorized_keys2.  Each line of the file
contains one key (empty lines and lines starting with a ‘#’ are ignored as
comments).  Public keys consist of the following space-separated fields:
options, keytype, base64-encoded key, comment.  The options field is
optional.  The keytype is “ecdsa-sha2-nistp256”, “ecdsa-sha2-nistp384”,
“ecdsa-sha2-nistp521”, “ssh-ed25519”, “ssh-dss” or “ssh-rsa”; the comment
field is not used for anything (but may be …
```
> Improve compatibility with authorized_keys file format

- nixos-infect
https://nixos.org/nix/install is in fact a redirect that returns `301` to `https://releases.nixos.org/nix/nix-X.X.X/install`. `curl` does not follow redirects by default, but it does with `-L` option.
No changes needed to `fakeCurlUsingWget()` because `wget` does follow `301` redirects by default.
> Add -L option to curl to follow 301 redirect

- nixos-infect
The '&&' causes this script to fail if $dotNetConf is not set due to 'set -e'
> Prefer to if to '&&'

- nixos-infect
This makes the resulting `hardware-configuration.nix` usable from a system that is a nix flake without having to replace that usage of `NIX_PATH` first.
**Longer explanation for this change:**
I had used nixos-infect to install NixOS on a DigitalOcean Droplet.
I then had to make a change like this manually and directly to the `hardware-configuration.nix`file so that I could turn that system into a flake-based system that re-uses the same `hardware-configuration.nix`file, because flake-based systems cannot depend on `NIX_PATH`. In my opinion this is a tedious manual step and it would be nice if people did not have to do this.
My proposal to fix that is this PR. I modified nixos-infect to directly produce that updated `hardware-configuration.nix` file and tested that the install still works …
> avoid using NIX_PATH in resulting hardware-configuration.nix

- nixos-infect
This allows lucky people on NVMe machines to `nixos-infect` successfully. Firstly by considering an NVMe device as a booting possibility, then ensuring the kernel module is present in the initrd to allow booting from it as a root device.
On a side note, I do have a complete branch @ https://github.com/risicle/nixos-infect/tree/ris-phoenixnap-bmc adding support for phoenixnap's "bare metal cloud" product, but it involves a significant addition - using a `jq` script to convert a netplan yaml config into a nixos `networking` configuration, and I don't know how you'd feel about incorporating this. Perhaps it would be better to keep it as a fork? Up to you really.
> Add basic NVMe support

- nixos-infect
While looking at my configuration, I noticed that `prefixLength` was incorrectly set to 32. While I haven't tested it, I think this misconfiguration makes every host within this very broad subnetwork (but outside your local network) unreachable.
> Fix prefixLength for route of IPv6 gateway

- README.md
The information about OpenVZ might not be correct per https://github.com/deepfire/nixos-wiki/blob/master/Install%20NixOS%20as%20OpenVZ%20guest.page
I had added it earlier but it seems wrong
> Removed potentially misleading information

- README.md
- nixos-infect
I was wondering whether it should also default to `21.05-small`, that's what I use in all my servers.
Thanks for making nixos-infect, it's been of great use!
> Update default nix to latest stable 21.05

- nixos-infect
Limited utility for most people but if there are (dumb) people like me whose first run of scripts precedes the first read of the manual and are users of sudo, this might be a tiny bit helpful. This (should) work(s) under two scenarios: `sudo nixos-infect` and `sudo su` followed by `./nixos-infect`. 
E.g.
```
ubuntu@nixos:~$ cat blah.sh
#!/bin/bash
whoami
echo $SUDO_USER
echo $HOME
ubuntu@nixos:~$ sudo ./blah.sh
root
ubuntu
/root
ubuntu@nixos:~$ sudo su
root@nixos:/home/ubuntu# ./blah.sh
root
ubuntu
/root
```
Thank you for creating this, it's such a life saver.
> Add a search path /home/$SUDO_USER/ for ssh keys

- nixos-infect
It was a tentative to make it work on Amazon Lightsail, but this is not enough. After reboot, the host does not come back. As Lightsail does not provide a console, I just gave up.
> Also check for /dev/xvda (Xen)

- nixos-infect
`nixos-rebuild` may consume more than 1GB memory even on a freshly-installed NixOS machine. This causes some "budget" machine with insufficient (e.g. less than 1GB) memory suffer from frequent interruption due to nix being killed by LMK. nixos-infect does enable extra swap during installation, but this is not the case with the new system.
Enabling zram (via `zramSwap.enable`) would make it less painful for those machines. Also it is recommended for most machines since the advantages surpass the disadvantages.
> Enable `zramSwap.enable` by default

- nixos-infect
Doesn't work everywhere with swapon, e.g. osuosl openstack cluster.
Without swap it can succeed though, it's not a hard prerequisite for the
infection to take effect.
> infect: have swap usage optional

- nixos-infect
Nix install script should be parsed by a Bourne-like shell, like bash
or sh. If the user invokes the script using a Korn shell or a Z Shell,
the script won't work. Nix documentation says to use "sh".
> Using sh instead of $SHELL

- README.md
- nixos-infect
This allows the user to checkout their own git repo and add that to NIXOS_LUSTRATE prior to infection.
From there, either NIXOS_IMPORT is supplied to invoke users own configuration, or NIXOS_CONFIG can now be overriden.
> Improve flexibility, enable pre-setting NIXOS_CONFIG, & NIXOS_LUSTRATE

- README.md
- nixos-infect
This required adding some modules to available kernel modules. Maybe we want to run `nixos-generate-config` to get required ones in the script in the future?
> Added cockbox support and documentation

- nixos-infect
When lustrating another machine, you usually are already connected by SSH. Thus, you usually already trusted that machine's keys.
With this patch, those keys are kept, so after booting into nixos, you still connect to the same trusted IP+Keys combination.
@moduon MT-904
> feat: respect old machine ssh host keys

- nixos-infect
This is required when infecting VMs based on VMware Paravirtual SCSI on VMware vSphere ESXi hosts
> Add vmw_pvscsi kernel module

- nixos-infect
Fix https://github.com/elitak/nixos-infect/issues/117 (caused by https://github.com/elitak/nixos-infect/pull/115) by not including vmw_pvscsi in boot.initrd.availableKernelModules no aarch64.
I have been able to install nixos successfully on AMD and Ampere instances on Oracle Cloud using this.
> Only include vmw_pvscsi on x64_64

- nixos-infect
This seems to be caused by the install script putting the entire hostname in `networking.hostName` when it should separate out the domain name into `networking.domain`.
Note that these changes will set `networking.domain` to `""` if the domain is empty. This is okay, NixOS appears to accept it in my tests.
<details>
I started with a fresh VM on Contabo but it likely isn't a contabo-only issue. Contabo appends a domain name to the end of their fresh servers.
```
root@vmi1086306:~# apt show hostname
Package: hostname
Version: 3.23
Priority: required
Essential: yes
Section: admin
Maintainer: Michael Meskes <meskes@debian.org>
Installed-Size: 51.2 kB
Pre-Depends: libc6 (>= 2.4)
Breaks: nis (<< 3.17-30)
Replaces: nis (<< 3.17-30)
Tag: implemented-in::c, interface::commandline, role::program, …
```
> Fix installation with FQDNs

- nixos-infect
When running nixos-infect on Oracle Linux 8 (on Oracle Cloud, with both AMD and ARM), I found that sshd refused to start when NixOS booted, because the private ssh host keys were 640 instead of 600 (i.e. `-rw-r-----` instead of `-rw-------`.
With this patch, I was able to run nixos-infect on Oracle Linux, and connect via ssh after rebooting.
> Fix ssh host key permissions on Oracle Linux

- README.md
Hi,
thanks a lot for your script, this is good stuff! I tried it with German provider Windcloud and documented my findings.
I got it working the the auto-generated networking.nix (as needed by DigitalOcean).
I guess a clean approach would be to add `windcloud` as a provider in the shell script; something like
```bash
[ "$PROVIDER" = "windcloud" ] && doNetConf=y # windcloud requires detailed network config to be generated  
```
(Or change the DO-if-statement). I'm happy to introduce something here but I did not want to do this until feedback from you.
> Add Windcloud as provider

- README.md
- changeset adds success testing for [Liga Hosting](https://ligahosting.ro)
- swaps nixos channel to `22.11` to keep in parity with upstream
- no regressions noted
@elitak
> adds liga hosting

- README.md
- nixos-infect
Fixes #106 
Implemented solution mentioned by @bramd in [the answer](https://github.com/elitak/nixos-infect/issues/106#issuecomment-1171543602):
- Ability to generate network config for Hetzner Cloud (passing `PROVIDER=hetznercloud`)
- Setting `networking.defaultGateway6.interface` in `networking.nix`
I tested the changes on Hetzner (Debian 11) and it works - I can ping:
Before the changes:
> fix: generate network config for Hetzner Cloud

- README.md
Use the current stable NixOS version in the installation instructions for Hetzner.
I've tested this with a new server instance.
> Update NixOS version for Hetzner

- nixos-infect
The official Nix installer will [add `nixpkgs-unstable` channel](https://github.com/NixOS/nix/blob/2ef99cd10489929a755831251c3fad8f3df2faeb/scripts/install-nix-from-closure.sh#L204-L215) unless run with `--no-channel-add` option. This seems unnecessary and only slows down installation as nixos-infect is adding channels just below.
> Do not add channel when installing Nix

- nixos-infect
If a `authorized_keys` file is empty or does not contain valid keys the rest of the illegible files are skipped. This change will make sure all files are checked until at least one key is found.
> Continue with next file if no keys are found

- nixos-infect
DigitalOcean now adds an SSH key containing double-quotes, which breaks nixos-infect.  This commit fixes this by using two single-quotes instead of a double-quote to wrap the SSH public key lines.
> Fix DigitalOcean installation

- README.md
I've spent non-trivial time trying to infect various versions of oracle linux and ubuntu only to figure out that 22.05 works better for that.
> Add a recent oracle cloud update

- nixos-infect
When spinning up two resources on the same VPC, my eth1 interface (the VPC's private IP range) did not get configured. Have tested on 15 Jul 2023 on DO and it has fixed my issue.
> eth1 does not get configured on DigitalOcean when using a VPC

- nixos-infect
This prevents install failure when the key was transferred from Windows, as they contains `\r`.
> Automatically trim auth keys.

- nixos-infect
As described in  issue #170 , it seems that trimming a key string removes too many spaces. The authorized keys format assumes that each line is arguments separated by a space. Xargs should leave it in this format, removing unnecessary whitespace characters.
> Fix SSH keys formatting

- nixos-infect
The idea is to automate provider detection when using curl and not cloud-init, since most providers add their own easily-detectable shenanigans
(The alternative would be to warn about setting PROVIDER manually, but that is more effort for the user)
Ref: https://github.com/elitak/nixos-infect/issues/173#issuecomment-1745921769
This was tested on CAX11
> Add provider autodetection for hetzner

- README.md
The user data approach dropped me in an inconsistent state. Nix installed, but other files were unaffected.
Ubuntu 22.04 (LTS) x64 worked perfectly, on the other hand.
> readme/DO: Mark ubuntu 23.10 as failure

- nixos-infect
> chore: Rename boot.cleanTmpDir to boot.tmp.cleanOnBoot

- nixos-infect
This pull request closes #183. I have already tested this change in AWS Lightsail with Ubuntu 22.04.
The boot device has been changed to:
```
NAME         MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
...
nvme0n1      259:0    0    40G  0 disk
├─nvme0n1p1  259:1    0  39.9G  0 part /
├─nvme0n1p14 259:2    0     4M  0 part
└─nvme0n1p15 259:3    0   106M  0 part /boot/efi
```
After rebooting the instance, the NixOS has been installed successfully.
```
Linux ip-<redact>.ap-southeast-1.compute.internal 5.15.119 #1-NixOS SMP Wed Jun 28 08:29:53 UTC 2023 x86_64 GNU/Linux
```
> change lightsail boot device to /dev/nvme0n1

- nixos-infect
Close https://github.com/elitak/nixos-infect/issues/160
Fix incorrect handling of sk-variant keys when reading authorized keys
Fix a security issue with the commented out ssh key
According to [specification](http://man.he.net/man5/authorized_keys) there are two additional variants that need to be handled:
```
sk-ecdsa-sha2-nistp256@openssh.com
sk-ssh-ed25519@openssh.com
```
Sed regular expressions are quite limited, and it wasn't possible to force the first group to match the longest expression.
The way this was handled was by observing that either:
1) a line starts with an option list (as per specification) and has a space delimited _sk-_, _ecdsa-_ or _ssh_ prefix
2) a line starts with an above-mentioned prefix
3) a line starts with a comment
Option 1) is the only one that we need to …
> fix: Authorized keys parsing and extraction

- nixos-infect
This change allow users to specify a custom nix install URL to use another nix version than the latest stable or to use another installer script.
> Add option to use a custom nix install URL
